version: "3.7"

x-local-common-variables: &local-common-variables
  SPREADSHEET_ID: ${SPREADSHEET_ID}
  RANGE_NAME: ${RANGE_NAME}
  PROGRAM_DELAY_SEC: ${PROGRAM_DELAY_SEC}
  CURRENCY_SEARCH_STRING: ${CURRENCY_SEARCH_STRING}
  API_KEY: ${API_KEY}
  BOT_TOKEN: ${BOT_TOKEN}
  CHAT_ID: ${CHAT_ID}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}


services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend-grabber:
    build:
      context: ./backend
      args:
        ENV_NAME: grabber
    environment:
      <<: *local-common-variables
    depends_on:
      - db

  backend-api:
    build:
      context: ./backend
      args:
        ENV_NAME: api
    environment:
      <<: *local-common-variables
    depends_on:
      - db
      - backend-grabber

  frontend:
    build:
      context: ./frontend/orderer
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    command: [ "nginx", "-g", "daemon off;" ]
    ports:
      - 8003:80
    depends_on:
      - backend-api

volumes:
  postgres_data:
